### PR TITLE
Fix text align center issue in Yahoo Webmail

### PR DESCRIPTION
**Pull request by hoducha**
The following css from Yahoo Webmail affects all paragraphs inside `<center>` tag so they are center aligned.
```css
.undoreset center {
    display: block;
    text-align: center;
}
```

### CODE REVIEW

**Comment by TedGoas** [comment]
@hoducha Can you provide a bit more detail / provide a screenshot of what is broken? I don't see center aligned text in Yahoo! Webmail.

chromeyahoo-vertical-allowed-1366

**Comment by hoducha** [comment]
In your screenshot, the text in the first 2 paragraphs are center aligned while they should be left aligned as displayed in other mail clients. The following is the screenshot of the cerberus-fluid template in Yahoo! Webmail.



**Expected result:**

**Comment by TedGoas** [comment]
@hoducha Great, thanks for clarifying! For some reason, Litmus wasn't displaying the issue. Here's Yahoo in Chrome via Litmus:

screen shot 2017-02-10 at 7 37 31 am
 
---

Even though Litmus wasn't showing Yahoo as broken, it **was showing older Outlook as broken**:

screen shot 2017-02-10 at 7 37 49 am

---

So something is wrong. I tested the Fluid template is actual Yahoo and saw the error:

screen shot 2017-02-10 at 7 39 37 am

---

I'll merge this shortly. Thank you for uncovering this, fixing it, and tidying up my rogue whitespaces :)

**Comment by hoducha** [comment]
Thanks @TedGoas. :)

**Pull request merged**
