### PR TITLE
clean up tabs and spacing

### PR DESCRIPTION
**Pull request by dyspop**
Just a friendly PR to clean this up.

You mentioned trailing spaces but they're only in archived versions. I left all the archived documents intact.

### CODE REVIEW

**Comment by TedGoas** [comment]
@dyspop Hey did you use a tool for this? I've been looking for a Coda plugin but can't find a good one. Might just use Sublime?

`replace all tabs with spaces` - Not a fan of spaces. I am working on converting everything to `Ta
b width 4`.

**Comment by dyspop** [comment]
I used sublime.

**Comment by TedGoas** [comment]
@dyspop I mentioned above that I'd been working on converting everything to `tab 4 indentation`. I used Sublime but realized that the indentation was still pretty screwed up in a lot of places (by human error, not Sublime). I also a number of other things like CSS spacing and code comments.

I hope you don't mind if I close this PR. You've been tremendously helpful in helping sort this out.

**Comment by dyspop** [comment]
Of course I don't mind, it's yours. I can submit tab 4 very quickly if you like. 

There is a decision to make about how to treat mso comments etc, no?

**Comment by TedGoas** [comment]
@dyspop Yep, I [submitted my change](https://github.com/TedGoas/Cerberus/commit/506eec1da229fca1749154b89c3a080feab00d76), if you'd like to review.

**Pull request closed without merging**
